# Generated by Django 3.0.4 on 2020-03-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Прикрепление',
                'verbose_name_plural': 'Прикрепления',
                'ordering': ['file'],
            },
        ),
    ]
